#!/bin/bash
set -e

export PATH=${PWD}/scripts:${PWD}/vendor:${PATH}
export PYTHONPATH=${PWD}:${PYTHONPATH}

PRODUCT="integration"

# Source config
source cloudformation.cfg

remove() {
    aws cloudformation delete-stack --stack-name ${stack_name}
    aws cloudformation wait stack-delete-complete --stack-name ${stack_name}
}

run() {
    _print_banner_message "Creating CloudFormation Stack"
    aws cloudformation create-stack --stack-name ${stack_name} \
        --template-body ${template_body} \
        --parameters ParameterKey=Region,ParameterValue=${region} \
            ParameterKey=VpcId,ParameterValue=${vpc_id} \
            ParameterKey=Environment,ParameterValue=${environment} \
            ParameterKey=Product,ParameterValue=${PRODUCT} \
            ParameterKey=KeyName,ParameterValue=${key_name} \
            ParameterKey=EC2DockerEngineImageId,ParameterValue=${ami_id} \
            ParameterKey=EC2LaunchSubnetGroup,ParameterValue=${subnet_ids} \
            ParameterKey=EC2LaunchSecurityGroup,ParameterValue=${security_grps} \
            ParameterKey=EC2InstanceProfile,ParameterValue=${ec2_role} \
            ParameterKey=EC2InstanceType,ParameterValue=${ec2_type}

    aws cloudformation wait stack-create-complete --stack-name ${stack_name}

    _print_banner_message "Setup Docker Engine Swarm Cluster"
    # Sync available instances
    machine --confdir ${MACHINE_CONFDIR} aws --region ${region} config sync --vpc-id ${vpc_id} -f

    # Use one of the instance to issue docker swarm command
    nodes=$(_get_nodes)
    eval $(machine --confdir ${MACHINE_CONFDIR} env ${nodes[0]})

    # Create Swarm Mode cluster from provided nodes
    deploy-swarm-cluster setup --cert ${CERT} --network ${NETWORK} ${nodes}

    _print_banner_message "Deploy Mongo Cluster Members"
    # Deploy mongodb service
    deploy-mongo-repl go --network ${NETWORK} --replSet ${REPL_SET}

    _print_banner_message "Configure Mongo Replication Cluster"
    # Setup mongodb replication cluster
    deploy-mongo-repl setup --network ${NETWORK} --replSet ${REPL_SET}
}

show() {
    aws cloudformation describe-stacks --stack-name ${stack_name} | jq -r '.Stacks | .[0].Outputs | .[]'
}

_print_banner_message() {
    cat <<EOF

------------------------------------
${1}
------------------------------------

EOF
}

_register_elb() {
    # Output ELB register command
    echo $(aws cloudformation describe-stacks --stack-name ${stack_name} | jq -r '.Stacks | .[0].Outputs | .[] | select(.OutputKey | contains("RegisterELBCommand")) | .OutputValue')
}

_get_nodes() {
    # Output provisioned nodes
    echo $(aws cloudformation describe-stacks --stack-name ${stack_name} | jq -r '.Stacks | .[0].Outputs | .[] | select(.OutputKey | contains("Manager")) | .OutputValue')
}

_help() {
    echo "deploy-cloudformation [run <product_name>|register|rm|show|help] --cert <key> --network <overlay_network> --replSet <replica_set_name>"
}

_help_and_exit() {
    exit_code=${1:-0}; _help; exit ${1}
}

while [ $# -gt 0 ]; do
    case ${1} in
        --cert)
            shift 1; CERT=$1; shift 1 ;;

        --network)
            shift 1; NETWORK=$1; shift 1 ;;

        --replSet)
            shift 1; REPL_SET=$1; shift 1 ;;

        rm)
            shift 1; func="rm"; ;;

        run)
            shift 1; func="run"; PRODUCT=$1; shift 1 ;;

        register)
            shift 1; func="register"; ;;

        show)
            shift 1; func="show"; ;;

        -h|--help|help)
            _help_and_exit ;;

        *)
            echo "Refuse to process $@; Unexpected arguments/flag"
            _help_and_exit 1 ;;
    esac
done

case ${func} in
    rm)
        exist=$(aws cloudformation describe-stacks --stack-name ${stack_name} &>/dev/null && echo "yes" || echo "no")
        if [ ${exist} = "no" ]; then
            echo "nothing to remove"
        else
            echo -e "\nYou are about to destroy CloudFormation stack ${stack_name}\n"
            read -p "Repeat the name to confirm your action: " challenge
            case ${challenge} in
                ${stack_name}) echo "running..."; remove; echo "done"; ;;
                *) echo "canceled" ;;
            esac
        fi
        exit 0 ;;
    run)
        run; exit 0 ;;
    register)
        _register_elb; exit 0 ;;
    show)
        show; exit 0 ;;
    *)
        echo "Please specify an action!"
        _help_and_exit 1 ;;
esac
