[template]
src = "cloudformation.cfg.tmpl"
dest = "cloudformation.cfg"
keys = [
    "/devops/ami_id",
    "/devops/ec2_role",
    "/devops/ec2_type",
    "/devops/environment",
    "/devops/key_name",
    "/devops/region",
    "/devops/stack_name",
    "/devops/subnet_ids",
    "/devops/security_grps",
    "/devops/template_body",
    "/devops/vpc_id"
]
