#!/usr/bin/env python

import json
import os
import subprocess
import sys

info = json.load(sys.stdin)

Parameters = {}
Resources = {}
for stacks in info["Stacks"]:
    for parameters in stacks["Parameters"]:
        Parameters[parameters["ParameterKey"]] = parameters["ParameterValue"]

    for output in stacks["Outputs"]:
        desc = output["Description"]

        meta = Resources.get(desc)
        if meta is None:
            Resources[desc] = {}

        key = output["OutputKey"].split(desc)[0]
        val = output["OutputValue"]

        Resources[desc][key] = val

for k, v in Resources.iteritems():
    if "PrivateIp" not in v or "PublicIp" not in v or "Name" not in v:
        continue

    keyName = os.path.expanduser("~/.ssh/{KeyName}.pem".format(**Parameters))

    args = [ "./vendor/machine", "--user", "ubuntu", "--cert", keyName, "create", "generic", "--no-install", "--driver", "aws", "--host", v["PublicIp"], "--altname", v["PrivateIp"], v["Name"] ]

    proc = subprocess.Popen(args, stdout=subprocess.PIPE)
    for line in proc.stdout:
        print line
